export enum Categorias {

    CARDIOLOGISTA = 0,
    CLINICO = 1,
    DERMATOLOGISTA = 2,
    GERIATRA = 3,
    GINECOLOGISTA = 4,
    OFTALMOLOGISTA = 5,
    PEDIATRA = 6,
    PSIQUIATRA = 7,
    OTORRINOLARINGOLOGISTA = 8,
    ONCOLOGISTA = 9,
    ORTOPEDISTA = 10,
    DENTISTA = 11,
}

// CARDIOLOGISTA = 'cardiologista',
//     CLINICO = 'clinico',
//     DERMATOLOGISTA = 'dermatologista',
//     GERIATRA = 'geriatra',
//     GINECOLOGISTA = 'ginecologista',
//     OFTALMOLOGISTA = 'oftalmologista',
//     PEDIATRA = 'pediatra',
//     PSIQUIATRA = 'psiquiatra',
//     OTORRINOLARINGOLOGISTA = 'otorrinolaringologista',
//     ONCOLOGISTA = 'oncologista',
//     ORTOPEDISTA =  'ortopedia',
//     DENTISTA = 'dentista',